# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:59
from __future__ import unicode_literals

import cut_link.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CutURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=220, validators=[cut_link.validators.validate_url])),
                ('shortlink', models.CharField(blank=True, max_length=15, unique=True)),
                ('pub_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
