# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cut_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuturl',
            name='shortlink',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
