# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cut_link', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuturl',
            old_name='timestamp',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='cuturl',
            name='updated',
        ),
    ]
