# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cut_link', '0002_auto_20170129_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuturl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
